version: 2

models:
  - name: mart_weather_hourly
    description: "Витрина почасовых данных о погоде (текущие + прогнозы)"
    config:
      tags: ['marts', 'hourly']
    columns:
      - name: city
        description: "Город"
        tests:
          - not_null

      - name: observation_timestamp
        description: "Временная метка наблюдения"
        tests:
          - not_null

      - name: data_type
        description: "Тип данных: current или forecast"
        tests:
          - not_null
          - accepted_values:
              values: ['current', 'forecast']

      - name: temperature_celsius
        description: "Температура в градусах Цельсия"
        tests:
          - not_null

      - name: wind_direction_cardinal
        description: "Направление ветра (стороны света)"
        tests:
          - accepted_values:
              values: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW', 'Unknown']

  - name: mart_weather_daily_avg
    description: "Витрина дневной агрегированной статистики по городам"
    config:
      tags: ['marts', 'daily', 'aggregated']
    tests:
      - dbt_utils.expression_is_true:
          expression: "max_temperature_celsius >= min_temperature_celsius"
      - dbt_utils.expression_is_true:
          expression: "temperature_range >= 0"
    columns:
      - name: city
        description: "Город"
        tests:
          - not_null

      - name: observation_date
        description: "Дата наблюдений"
        tests:
          - not_null

      - name: avg_temperature_celsius
        description: "Средняя температура за день"
        tests:
          - not_null

      - name: min_temperature_celsius
        description: "Минимальная температура за день"
        tests:
          - not_null

      - name: max_temperature_celsius
        description: "Максимальная температура за день"
        tests:
          - not_null

      - name: temperature_range
        description: "Разница между макс и мин температурой"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: observations_count
        description: "Количество наблюдений за день"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"

  - name: mart_cities
    description: "Справочник городов с базовой статистикой"
    config:
      tags: ['marts', 'cities', 'dimension']
    columns:
      - name: city
        description: "Название города (уникальный ключ)"
        tests:
          - not_null
          - unique

      - name: country
        description: "Страна"
        tests:
          - not_null

      - name: latitude
        description: "Широта"
        tests:
          - not_null

      - name: longitude
        description: "Долгота"
        tests:
          - not_null

      - name: first_observation
        description: "Первое наблюдение"
        tests:
          - not_null

      - name: last_observation
        description: "Последнее наблюдение"
        tests:
          - not_null

      - name: days_tracked
        description: "Количество дней наблюдений"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
