version: 2

models:
  - name: stg_weather_current
    description: "Staging модель для текущей погоды - нормализованные данные из raw слоя"
    tests:
      # Кастомный тест на уровне модели
      - consistent_city_coordinates:
          city_column: city
          lat_column: latitude
          lon_column: longitude
          tolerance: 0.1
    columns:
      - name: id
        description: "Первичный ключ"
        tests:
          - not_null
          - unique

      - name: weather_id
        description: "MongoDB ObjectId в виде строки"
        tests:
          - not_null

      - name: latitude
        description: "Широта локации"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= -90 and <= 90"

      - name: longitude
        description: "Долгота локации"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= -180 and <= 180"

      - name: city
        description: "Название города"
        tests:
          - not_null

      - name: temperature_celsius
        description: "Температура в градусах Цельсия"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> -100 and < 60"

      - name: feels_like_celsius
        description: "Ощущаемая температура"
        tests:
          - reasonable_feels_like_difference:
              max_difference: 15

      - name: humidity_percent
        description: "Влажность в процентах"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0 and <= 100"

      - name: created_at
        description: "Дата создания записи"
        tests:
          - not_null

      - name: updated_at
        description: "Дата последнего обновления"
        tests:
          - not_null

  - name: stg_weather_forecast
    description: "Staging модель для прогнозов погоды - развернутые данные по часам"
    columns:
      - name: forecast_id
        description: "ID прогноза из MongoDB"
        tests:
          - not_null

      - name: latitude
        description: "Широта локации"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= -90 and <= 90"

      - name: longitude
        description: "Долгота локации"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= -180 and <= 180"

      - name: city
        description: "Название города"
        tests:
          - not_null

      - name: forecast_timestamp
        description: "Временная метка прогноза"
        tests:
          - not_null

      - name: hour_offset
        description: "Смещение в часах от момента создания прогноза"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: temperature_celsius
        description: "Прогнозируемая температура"
        tests:
          - dbt_utils.expression_is_true:
              expression: "> -100 and < 60"
