name: 'weather_analytics'
version: '1.0.0'

profile: 'weather_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  weather_analytics:
    stg:
      +materialized: incremental
      +schema: stg
      +incremental_strategy: delete+insert

    ods:
      +materialized: incremental
      +schema: ods
      +incremental_strategy: merge

    dm:
      +materialized: incremental
      +schema: dm
      +incremental_strategy: merge

  # Elementary data quality monitoring
  elementary:
    +schema: elementary
